# -*- coding: utf-8 -*-
"""
Created on Tue Jan  2 17:15:59 2024

@author: yyyyyyyyyyyyyyyyyyyy
"""

#When you create a Tkinter application, you must call window.mainloop() to start the event loop. 
#During the event loop, your application checks if an event has occurred.
#If so, then it’ll execute some code in response.

#The event loop is provided for you with Tkinter, so you don’t have to write any code that checks for events yourself.
#However, you do have to write the code that will be executed in response to an event.
#In Tkinter, you write functions called event handlers for the events that you use in your application.

#Assume there’s a list called events that contains event objects.
#A new event object is automatically appended to events every time an event occurs in your program. 
#You don’t need to implement this updating mechanism.
#It just automatically happens for you in this conceptual example.
#Using an infinite loop, you can continually check if there are any event objects in events:
    

# Create a window object
import tkinter as tk

window = tk.Tk()

def handle_keypress(event):
    """Print the character associated to the key pressed"""
    print(event.char)

# Bind keypress event to handle_keypress()
window.bind("<Key>", handle_keypress)

window.mainloop()

# can bind to any  widget
def handle_click(event):
    print("The button was clicked!")

button = tk.Button(text="Click me!")

button.bind("<Button-1>", handle_click)



#.bind() always takes at least two arguments:
#An event that’s represented by a string of the form "<event_name>",
#where event_name can be any of Tkinter’s events
#An event handler that’s the name of the function to be called whenever the event occurs
    
#Right now, the event loop that you’ve created doesn’t do anything with event.
#Let’s change that. Suppose your application needs to respond to keypresses.
#You need to check that event was generated by a user pressing a key on their keyboard, 
#and if so, pass event to an event handler function for keypresses.
#Update your event loop to use window.mainloop()
# instead of your own event loop:
   
    
    
    
    