# -*- coding: utf-8 -*-
"""
Created on Thu Jan 11 12:10:10 2024

@author: yyyyyyyyyyyyyyyyyyyy
"""
import networkx as nx
import matplotlib.pyplot as plt
G= nx.star_graph(1)
G.add_nodes_from([1, 2, 3,4,5,6])
G.add_edges_from([(1, 2), (1, 3),(1,3),(1,4),(4,5),(5,6),(2,6)])
# swap out the main textbox deleting it 
# generate the network
# then insert the network.
# then insert the image in its place that is generated by running this code.
# problem_list_dictionory = {}
#G = nx.Graph()
#G= nx.star_graph(1)
#G.add_nodes_from([1, 2, 3,4,5,6])
#G.add_edges_from([(1, 2), (1, 3),(1,3),(1,4),(4,5),(5,6),(2,6)])
#G.add_edge(1, 2)
color_map=[]
fig, ax = plt.subplots()
pos=  nx.spring_layout(G, seed=52) 

for node in G:
    time_stamp
    # how do we identify layers
    # we identify htem by 
    # get quality 
    # save prolbem root note each of its qualtites as second level and then build from here
    # how do i identify problem root
    # insert problem: or something to the front or maybe
    if problem_layer:
        #light blue
    if layer1:
        #yellow
    
    if layer2:
        #orange
    
    if layer3:
        # pink
    if layer4:
        # red
    if layer5:
        #light blue
        
    if node <2:
        color_map.append('#A0CBE2')  
        continue
    color_map.append('red')  
nx.draw_networkx(G,pos, with_labels=True, node_color=color_map, font_weight='bold',edge_color='#A0CBE2',font_color='black',edge_cmap= plt.cm.Blues)
ax.set_facecolor('deepskyblue')
ax.axis('off')
fig.set_facecolor('white')
plt.show()
# different layers can have different colored nodes
# first layer red, then blue, then green, yellow

#subax2 = plt.subplot(122)
#nx.draw_networkx(G, nlist=[range(5, 10), range(5)], with_labels=True, font_weight='bold')